# URL Translator Backend Configuration
# Default configuration file

[server]
port = 3002
host = "0.0.0.0"
workers = 4
max_connections = 1000
request_timeout_seconds = 30

[database]
max_connections = 10
min_connections = 2
connect_timeout_seconds = 10
max_lifetime_seconds = 3600
idle_timeout_seconds = 600

[redis]
max_connections = 10
connect_timeout_seconds = 5
command_timeout_seconds = 10
default_ttl_seconds = 3600

[meilisearch]
connect_timeout_seconds = 10
request_timeout_seconds = 30
index_prefix = "url_translator_"
max_search_results = 100

[auth]
jwt_expiry_hours = 24
password_min_length = 8
max_login_attempts = 5
lockout_duration_minutes = 15

[rate_limiting]
requests_per_minute = 60
burst_size = 10
window_size_seconds = 60

[translation]
max_text_length = 50000
max_batch_size = 100
default_timeout_seconds = 30
max_concurrent_requests = 5

[api]
max_file_size_mb = 10
allowed_file_types = ["txt", "md", "html"]
default_page_size = 20
max_page_size = 100

[logging]
level = "info"
format = "json"
file_rotation = "daily"
max_log_files = 7